user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzE=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: "vk1.a.UXtr-eondruIUMpZr0AkKuZmg5_oSsiytZCye3bxchQU4v39L5WbVFHJWxsMcfru3DfXdPtPVDrJp4fe49eEaZwgTwMb0c8aNahTLHeOO1ScBxVplpoIqLpFf6yvcVXcUBHkSoolDN19f8mIX0a6UDB_GxGVPg8z3XNRTE7t1p7_K4xe5TYezlCSVtvLyuKRxlxeE_GwbNa-B3gqltw5-w"
  group_id: 236013203


